#server:
 # port: 8989 #当前应用的端口号
#Logging
spring:
  profiles:
    active: dev #context-path: /springboot #指定项目的应用名字
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_demo?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: utf-8
      enabled: true
 # data:
 #   mongodb:
 #     host: 127.0.0.1
 #     port: 27017
 #     database: test
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:config/logback.xml